# 1. directory
root_path: "/home/chenyu/SSMIS/data/Pancreas"
res_path: "./results/Pancreas"
# random seed
seed: 1377
test_interval_ep: 4


# 2. training

max_iterations: 15000
max_samples: 62
base_lr: 0.001
batch_size: 4
labeled_bs: 2
poly: True


# 3. supervision
ema_decay: 0.99
consistency: 2.0
consistency_rampup: 40
