# 1. directory
root_path: "/home/chenyu/SSMIS/data/LA"
res_path: "./results/LA"
# random seed
seed: 2027
test_interval_ep: 4


# 2. training
max_iterations: 15000
max_samples: 80
base_lr: 0.001
batch_size: 4
labeled_bs: 2
poly: True


# 3. supervision
ema_decay: 0.99
consistency: 2.0
consistency_rampup: 40
